### ISSUE TITLE
Aggiornamenti in vista?

### ISSUE THREAD

**Issue by rudj** [kbytesys/django_comuni_italiani#2]
ciao,
è possibile che arrivi un adeguamento di compatibilità a Django 2.0?

**Comment by kbytesys** [comment]
Si ci stavo lavorando, ma questo progetto ora ha una priorità minore rispetto al passato. Potrebbero volerci alcune settimane. ovviamente eventuali PR sono sempre bene accette!

**Comment by rudj** [comment]
ok, grazie, io stò facendo il passaggio in questo periodo, se riscontro
problemi e li risolvo ti sottoporrò le modifiche.

P.S.: grazie per il tuo lavoro
rudj

2018-03-26 10:02 GMT+02:00 Andrea Briganti <notifications@github.com>:

**Comment by udanieli** [comment]
@rudj se vuoi dare un'occhiata e fare qualche prova c'è un branch django2 nel mio fork. I commenti sono ben accetti (ovviamente [scriviamo lì](https://github.com/kbytesys/django_comuni_italiani/pull/3))

**Comment by kbytesys** [comment]
@udanieli @rudj scusatemi per il tremendo ritardo ma sono stato molto preso a lavoro. Durante le vacanze estive posso controllare la pr.

PS. Dato che avevo creato questo progetto per un'attività legata a un vecchio lavoro, attualmente non ho occasione di utilizzarlo se non aiutare la comunità. Se trovassimo un modo (devo studiare meglio github) per far si che il repository sia mantenuto in gruppo?

**Comment by udanieli** [comment]
Ciao @kbytesys, non preoccuparti del ritardo, immagino come vadano certe cose.
Sto utilizzando il fork su un progetto da un mesetto e finora tutto bene. Nel frattempo avevo fatto un altro piccolo adeguamento al sistema di `URLconf` che mi ero dimenticato di caricare sul repository.

Per quanto riguarda il mantenimento puoi aggiungere nel pannello _settings_  dei _collaborators_ che possono fare push, revisione PRs eccetera sul repository. Per l'elenco completo dei permessi dei collaboratori vedi la [documentazione ufficiale](https://help.github.com/articles/permission-levels-for-a-user-account-repository/#collaborator-access-on-a-repository-owned-by-a-user-account) a riguardo.
Buone vacanze!

**Comment by kbytesys** [comment]
@udanieli come promesso ti ho aggiunto tra i collaboratori e oggi aggiusto un po' il setup.py e la configurazione di travis per poter fare automaticamente il deploy su pypi.
