### ISSUE TITLE
Errore README?

### ISSUE THREAD

**Issue by Anatras02** [kbytesys/django_comuni_italiani#8]
Buongiorno, nel readme c'è scritto questo import
`from dal import autocomplete`

Ma cosa sarebbe dal?

**Comment by udanieli** [comment]
`dal` è [django-autocomplete-light](https://django-autocomplete-light.readthedocs.io/en/master/), una famosa libreria utilizzata in questo progetto che ti raccomando anche per i tuoi progetti. Serve, come dice il nome, per i suggerimenti (autocompletamento) quando compili un form e c'è un menù select con una marea di opzioni che non vuoi caricare tutto d'un fiato ma preferisci suggerire solo poche opzioni. Internet è pieno di questi menù a tendina "interattivi".
Esempio: scrivo `Lec` e lui pesca nel database con un `LIKE 'Lec%'` e ti ficca nel menù a tendina solo `Lecce`, `Lecco`, eccetera.
Altro caso d'uso: filtri con due menù a tendina collegati, es. in uno scegli la regione e poi una volta scelta la regione nell'altro menù a tendina puoi scegliere le province di quella regione.
