### ISSUE TITLE
Issue with birthdate and municipality date_created check

### ISSUE THREAD

**Issue by raymanzarek1984** [kbytesys/django_comuni_italiani#9]
Ciao,
apprezzo moltissimo questo modulo che mi ha aiutato moltissimo in un mio progetto personale.

Utilizzo la funzione encode() per generare un CF da confrontare con un altro CF dato in input.
Ho un problema: la data di nascita (antecedente) non va d'accordo con la data di creazione di un comune.

Allego uno screenshot con tutti i dati del caso:
![Issue on birthplace date_created](https://user-images.githubusercontent.com/1735565/222821259-4dde6edc-90d8-4643-8407-0bfe622d4d9d.png)

**Comment by udanieli** [comment]
La schermata che hai inviato sembra quella di un pacchetto chiamato [python-codicefiscale](https://github.com/fabiocaccamo/python-codicefiscale/blob/main/codicefiscale/codicefiscale.py), che non c'entra nulla con questo progetto. Dovresti aprire una richiesta lì.

Inoltre, se guardi nel [data model](https://github.com/kbytesys/django_comuni_italiani/blob/master/comuni_italiani/models.py) non ci sono proprio campi data o datetime di creazione di un comune.

**Comment by raymanzarek1984** [comment]
Perdon, ho fatto confusione.
Grazie per la comprensione.
